# PR Review with custom options
# Copy this file to .github/workflows/claude-review.yml in your repository

name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: drillan/claude-pr-reviewer@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # Use faster model for cost efficiency
          anthropic_model: claude-sonnet-4-5-20250929
          # Review in Japanese
          review_language: Japanese
          # Add custom review instructions
          custom_prompt: |
            Focus especially on:
            - Security vulnerabilities
            - Performance implications
            - API design consistency
